spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.sxqwmnqgjtsupfsyqief
spring.datasource.password=Shubham#057

spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# JWT Configuration
jwt.secret=mySecretKeyForJwtTokenGenerationAndValidationOfEcommerceApplication
jwt.expiration=86400000